import {chromium} from '@playwright/test';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {CIRCUIT,POIS} from '../src/story.js';
import {presentationFor} from '../src/dialogue-presentation.js';
import {STORY_CGS,personHeadshot,speakerPerson} from '../src/story-art.js';
import {DIALOGUES} from '../src/story.js';
const dir=process.env.QA_DIR?process.env.QA_DIR.replace(/\/$/,'')+'/':fileURLToPath(new URL('../output/qa/',import.meta.url));await mkdir(dir,{recursive:true});
const b=await chromium.launch({headless:true,channel:'chrome'});
const p=await b.newPage({viewport:{width:1440,height:900}});
const errors=[],failed=[],assetUrls=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(['script','stylesheet'].includes(r.request().resourceType()))assetUrls.push(r.url());if(r.status()>=400&&!r.url().endsWith('/.env'))failed.push({status:r.status(),url:r.url()});});
const BASE=process.env.GAME_URL||'http://localhost:5173';
const firstPerson=process.env.QA_CAMERA==='first';
const report={started:new Date().toISOString(),cameraMode:firstPerson?'first':'street',checks:[],screenshots:[],storyCGs:[],assetUrls,base:BASE,errors,failed};
const check=x=>{report.checks.push(x);console.log('PASS',x);};
async function snap(name){await p.waitForTimeout(280);await p.screenshot({path:dir+name+'.png'});report.screenshots.push(name+'.png');}
async function dialog(key,{replay=false}={}){let count=0,previousMemory=null,previousCG=null;while(await p.locator('#story-next').isVisible()){
 if(key){const {memory,cgId}=presentationFor(key,count,{replay});assert.equal(await p.locator('.story').evaluate(e=>e.classList.contains('in-world')),!memory,key+' line '+count);assert.equal(await p.locator('.story-art').isVisible(),memory);assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.getWorld().suspended),memory);
  const person=speakerPerson(DIALOGUES[key][count].who);
  assert.equal(await p.locator('#speaker-portrait').isVisible(),!memory&&Boolean(person));
  if(!memory&&person){const avatarId=await p.evaluate(()=>window.__JIANGCHENG__.getState().settings.avatarId);assert.equal(await p.locator('#speaker-portrait').getAttribute('src'),personHeadshot(person.id,avatarId));await p.locator('#speaker-portrait').evaluate(img=>img.decode());}
  if(cgId&&cgId!==previousCG){
   const cg=STORY_CGS.find(cg=>cg.id===cgId),progress=await p.locator('#story-progress').innerText();
   assert.ok(await p.locator('.story-art').evaluate((el,url)=>el.style.backgroundImage.includes(url),cg.url));
   await p.evaluate(async url=>{const image=new Image();image.src=url;await image.decode();},cg.url);
   await p.waitForFunction(expected=>window.__JIANGCHENG__.getAudio().music===expected,key==='ending'?'ending':'memory',{timeout:20000});await snap(`cg-${cgId}-dialogue`);await p.locator('#cg-inspect').click();
   assert.ok(await p.locator('.story.inspecting-cg').isVisible());assert.equal(await p.locator('.dialogue-box').isVisible(),false);await snap(`cg-${cgId}-full`);
   await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.getModal()),'story');assert.equal(await p.locator('#story-progress').innerText(),progress);assert.ok(await p.locator('#story-next').isVisible());
   if(!report.storyCGs.includes(cgId))report.storyCGs.push(cgId);
  }
  if(memory!==previousMemory){await snap(`dialogue-${key}-${count}-${memory?'memory':'world'}`);previousMemory=memory;}previousCG=cgId;}
 await p.locator('#story-next').click();if(++count>70)throw Error('dialogue loop');}return count;}
async function conversationFrame(name){await p.waitForTimeout(2100);const panel=await p.locator('.dialogue-box').boundingBox(),view=p.viewportSize(),data=await p.evaluate(()=>window.__JIANGCHENG__.getWorld());assert.ok(data.conversation,name+' has a live conversation');for(const actor of data.conversation.actors){assert.ok(actor.visible,name+' '+actor.id+' visible');assert.ok(actor.head.visible&&actor.feet.visible,name+' '+actor.id+' is in the camera');assert.ok(actor.head.x>24&&actor.head.x<view.width-24,name+' '+actor.id+' horizontally framed');assert.ok(actor.head.y>145&&actor.feet.y<panel.y-8,name+' '+actor.id+' unobscured by dialogue');}await snap(name);}

async function go(id){await p.locator('#map').click();await p.locator(`[data-place="${id}"]`).click();await p.locator('#map-go').click();await p.waitForFunction(id=>window.__JIANGCHENG__.getNearest()===id&&window.__JIANGCHENG__.getWorld().remainingRoute===0,id,{timeout:60000});await p.waitForTimeout(350);}
async function interact(){await p.locator('#interact').click();}
try{
 await p.goto(BASE);await p.locator('#boot').waitFor({state:'hidden',timeout:60000});await p.waitForTimeout(2000);await snap('01-title');check('Desktop title renders without missing assets');
 await p.locator('#journal').click();await p.locator('[data-tab="cg"]').click();assert.equal(await p.locator('.cg-card:disabled').count(),8);assert.equal(await p.locator('.cg-card img').count(),0);for(const cg of STORY_CGS)assert.ok(!(await p.locator('#journal-content').innerHTML()).includes(cg.url));await snap('00-locked-cg-collection');await p.locator('[data-tab="people"]').click();assert.equal(await p.locator('.person-card').count(),6);await p.locator('.person-card img').evaluateAll(images=>Promise.all(images.map(img=>img.decode())));await snap('00-character-directory');await p.locator('.close').click();check('New saves hide all CG spoilers and show six illustrated people');
 await p.locator('#intro-film').click();await p.locator('#cinematic').waitFor();await p.waitForFunction(()=>document.querySelector('#cinematic').readyState>=2);assert.ok(await p.locator('#cinematic').evaluate(v=>v.videoWidth>0));await snap('02-opening-video');await p.locator('#film-close').click();check('Opening video decodes');
 await p.locator('#sound').click();await p.locator('#start').click();if(firstPerson){await p.locator('#first-person').click();assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.getWorld().cameraMode),'first');}assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.canWalk(12,12)),false);assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.canWalk(-12,17)),false);check('Breakfast counter and repair workbench block walking through their models');await go('shop');await p.waitForTimeout(1500);await snap('03-reconstructed-shop');await interact();await conversationFrame('04-story-3d');await p.waitForFunction(()=>window.__JIANGCHENG__.getAudio().voice?.lineId==='intro-door',{},{timeout:20000});assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.getAudio().ducking),true);check('Narration decodes and ducks background music in the live 3D scene');
 const before=await p.evaluate(()=>window.__JIANGCHENG__.getWorld());await p.keyboard.press('Enter');assert.match(await p.locator('#story-progress').innerText(),/^02/);await p.waitForFunction(()=>window.__JIANGCHENG__.getAudio().voice?.lineId==='intro-key',{},{timeout:20000});await p.locator('#voice-replay').focus();await p.keyboard.press('Enter');assert.match(await p.locator('#story-progress').innerText(),/^02/);await p.locator('#story-prev').click();await p.keyboard.down('w');await p.waitForTimeout(350);await p.keyboard.up('w');const during=await p.evaluate(()=>window.__JIANGCHENG__.getWorld());assert.deepEqual(during.position,before.position);assert.ok(during.renderFrame>before.renderFrame);await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.getWorld().conversation),null);assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.getAudio().voice),null);assert.ok(await p.locator('#map').isVisible());await interact();await dialog('intro');check('Ordinary dialogue stays in live 3D; keyboard advances, movement pauses, exit restores controls');assert.ok(await p.locator('.circuit-grid').isVisible());
 await p.locator('#circuit-check').click();assert.match(await p.locator('#puzzle-feedback').innerText(),/没接上/);for(let i=0;i<CIRCUIT.length;i++)for(let n=0;n<(4-CIRCUIT[i].rot)%4;n++)await p.locator(`[data-tile="${i}"]`).click();await snap('05-radio-puzzle');await p.locator('#circuit-check').click();await snap('05-radio-success');await p.locator('[data-activity-continue]').click();await dialog();check('Radio puzzle rejects a broken circuit and accepts actual connectivity');
 // Performance-saving option is user-accessible, and the rest of the walkthrough exercises it.
 await p.locator('#settings').click();await p.locator('#set-quality').selectOption('low');await p.locator('.close').click();
 await go('community');await interact();assert.match(await p.locator('#dialogue-text').innerText(),/先去看看/);await dialog();check('Visiting community out of order does not bypass required help');
 await p.locator('#settings').click();await p.locator('#set-quality').selectOption('high');await p.locator('.close').click();await go('granny');await interact();await conversationFrame('dialogue-granny-desktop');await p.setViewportSize({width:390,height:844});await conversationFrame('dialogue-granny-mobile');await p.setViewportSize({width:1440,height:900});await dialog('granny');await p.locator('#order-check').click();assert.match(await p.locator('#puzzle-feedback').innerText(),/没连起来/);await p.locator('[data-up="1"]').click();await p.locator('[data-up="3"]').click();await p.locator('[data-up="2"]').click();await snap('06-memory-puzzle');await p.locator('#order-check').click();await snap('06-memory-success');await p.locator('[data-activity-continue]').click();await snap('07-memory-cg');await dialog('grannyMemory');check('Memory sequence puzzle and grandmother story complete');await p.locator('#settings').click();await p.locator('#set-quality').selectOption('low');await p.locator('.close').click();
 await go('chef');await interact();await conversationFrame('dialogue-chef-desktop');await dialog('chefIntro');for(const id of ['box','water','battery']){await go(id);await interact();}await go('chef');await interact();await dialog('chefMemory');check('All three supplies are reachable and breakfast memory completes');
 await go('dock');await interact();await conversationFrame('dialogue-dock-desktop');await dialog('dock');await p.locator('[data-choice="1"]').click();assert.ok((await p.locator('#choice-feedback').innerText()).length>10);await p.locator('[data-choice="0"]').click();await p.locator('[data-activity-continue]').click();check('Dock safety choice provides corrective feedback and story reward');
 await go('community');await interact();await conversationFrame('dialogue-community-desktop');await dialog('community');await p.locator('#pack-check').click();assert.match(await p.locator('#puzzle-feedback').innerText(),/再想一想/);for(const id of ['water','light','food','aid','contact'])await p.locator(`[data-pack="${id}"]`).click();await snap('08-emergency-kit');await p.locator('#pack-check').click();await snap('08-emergency-kit-success');await p.locator('[data-activity-continue]').click();await dialog('prepared');
 for(const id of ['riskWater','riskCable']){await go(id);await interact();await p.locator('[data-choice="1"]').click();assert.ok((await p.locator('#choice-feedback').innerText()).length>10);await p.locator('[data-choice="0"]').click();await p.locator('[data-activity-continue]').click();}check('Both risk sites reachable; unsafe actions cannot pass');
 await go('community');await interact();await dialog('checked');await go('shop');await interact();await dialog('ending');await snap('09-ending');assert.ok(await p.evaluate(()=>window.__JIANGCHENG__.getState().flags.includes('ending')));check('Full story reaches the ending through real UI navigation');await writeFile(dir+'completed-save.json',JSON.stringify(await p.evaluate(()=>window.__JIANGCHENG__.getState()),null,2));
 await p.locator('#ending-film').click();await p.waitForFunction(()=>document.querySelector('#cinematic')?.readyState>=2);assert.ok(await p.locator('#cinematic').evaluate(v=>v.videoWidth>0));await p.locator('#cinematic').evaluate(v=>{v.pause();v.currentTime=4;});await p.waitForTimeout(300);await snap('09-ending-video');await p.locator('#film-close').click();await p.locator('audio').evaluate(a=>a.load());await p.waitForFunction(()=>document.querySelector('audio')?.readyState>=2);assert.ok(await p.locator('audio').evaluate(a=>a.duration>10));check('Ending video and letter audio decode from local assets');
 await p.locator('#ending-walk').click();for(const id of ['clock','noodles','ferry','bridge','brick','photo']){await go(id);await interact();await p.locator('.close').click();}assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.getState().lore.length),6);check('All six Wuhan field notes reachable and collectible');
 assert.deepEqual([...report.storyCGs].sort(),STORY_CGS.map(cg=>cg.id).sort());check('All eight CGs decode at their authored narrative moments and return to 3D');
 await p.reload();await p.locator('#boot').waitFor({state:'hidden',timeout:60000});assert.ok(await p.evaluate(()=>window.__JIANGCHENG__.getState().flags.includes('ending')));assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.getState().lore.length),6);check('Refresh restores ending and collections');
 await p.locator('#start').click();await p.locator('#journal').click();await snap('10-journal');await p.locator('[data-memory="grannyMemory"]').click();await dialog('grannyMemory',{replay:true});await p.locator('.close').click();check('Completed memories replay without losing progress');
 const beforeGallery=await p.evaluate(()=>{const {flags,lore,supplies,milestones}=window.__JIANGCHENG__.getState();return {flags,lore,supplies,milestones};});
 await p.locator('#journal').click();await p.locator('[data-tab="cg"]').click();assert.equal(await p.locator('.cg-card:not(:disabled)').count(),8);await snap('10-unlocked-cg-collection');await p.locator('[data-cg="granny-table"]').click();assert.ok(await p.locator('#cg-prev').isDisabled());for(let i=0;i<7;i++)await p.keyboard.press('ArrowRight');assert.ok(await p.locator('#cg-next').isDisabled());await snap('10-gallery-final-cg');await p.keyboard.press('Escape');assert.ok(await p.locator('.cg-gallery').isVisible());await p.locator('.close').click();assert.deepEqual(await p.evaluate(()=>{const {flags,lore,supplies,milestones}=window.__JIANGCHENG__.getState();return {flags,lore,supplies,milestones};}),beforeGallery);check('Gallery unlocks survive reload; keyboard viewing preserves progress');
 for(const viewport of [{width:1920,height:1080},{width:390,height:844}]){await p.setViewportSize(viewport);await p.locator('#brand').click();await p.waitForTimeout(400);await snap(viewport.width===390?'11-mobile-title':'11-large-title');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('#start').click();await p.locator('#map').click();await snap(viewport.width===390?'12-mobile-map':'12-large-map');assert.ok(await p.locator('#map-go').isVisible());await p.locator('.close').click();}check('Desktop and mobile layouts have no horizontal overflow');
 await snap('13-mobile-world');
 const env=await p.request.get(BASE+'/.env');assert.ok([403,404].includes(env.status())||(env.status()===200&&(await env.text()).startsWith('<!doctype html>')));check('Server does not expose .env');
 if(firstPerson){assert.equal(await p.evaluate(()=>window.__JIANGCHENG__.getWorld().cameraMode),'first');check('First-person exploration survives the full story, memories, films, menus and save reload');}
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);check('No unhandled browser errors or failed asset requests');report.completed=new Date().toISOString();
}catch(e){report.failure=e.stack;console.error(e);await snap('failure');process.exitCode=1;}finally{await writeFile(dir+'browser-report.json',JSON.stringify(report,null,2));await b.close();}
