import test from 'node:test';
import assert from 'node:assert/strict';
import {CinemaTransport,cinemaAsset,cinemaCues,captionAt} from '../src/cinema-player.js';
class Medium extends EventTarget {
 constructor(){super();this.currentTime=0;this.duration=32;this.paused=true;this.ended=false;this.seeking=false;this.playbackRate=1;this.volume=1;this.muted=false;this.playCalls=0;this.pauseCalls=0;}
 async play(){this.playCalls++;this.paused=false;this.dispatchEvent(new Event('play'));}
 pause(){this.pauseCalls++;const was=this.paused;this.paused=true;if(!was)this.dispatchEvent(new Event('pause'));}
 emit(name){this.dispatchEvent(new Event(name));}
 removeAttribute(){}load(){}
}
function harness(){const video=new Medium(),tracks={music:new Medium(),effects:new Medium(),voice:new Medium()},errors=[];let ended=0;const transport=new CinemaTransport({video,tracks,preferences:{sound:true,musicVolume:.3,effectsVolume:.4,voiceVolume:.8},onError:e=>errors.push(e),onEnded:()=>ended++});return {video,tracks,transport,errors,ended:()=>ended};}
test('cinema assets are local and avatar variants resolve explicitly',()=>{assert.equal(cinemaAsset('https://invalid.test/a.mp3'),null);assert.equal(cinemaAsset('/media/../.env'),null);assert.equal(cinemaAsset({female:'/media/f.mp3',male:'/media/m.mp3'},'male'),'/media/m.mp3');});
test('caption intervals are validated and do not repeat at a cut boundary',()=>{const cues=cinemaCues([{start:1,end:2,text:'乙'},{start:0,end:1,text:'甲'},{start:0,end:-1,text:'bad'}]);assert.equal(cues.length,2);assert.equal(captionAt(cues,.9).text,'甲');assert.equal(captionAt(cues,1).text,'乙');assert.equal(captionAt(cues,2),null);});
test('all stems follow one video clock through play, pause, seek and rate changes',async()=>{const h=harness();await h.transport.play();for(const a of Object.values(h.tracks))assert.equal(a.paused,false);h.video.currentTime=5;h.transport.sync();for(const a of Object.values(h.tracks))assert.equal(a.currentTime,5);h.video.playbackRate=1.5;h.video.emit('ratechange');assert.equal(h.tracks.voice.playbackRate,1.5);h.transport.pause();for(const a of Object.values(h.tracks))assert.equal(a.paused,true);h.transport.seek(12);assert.equal(h.video.currentTime,12);for(const a of Object.values(h.tracks)){assert.equal(a.currentTime,12);assert.equal(a.paused,true);}h.transport.dispose();});
test('three volumes remain independent; master mute silences without losing clock position',async()=>{const h=harness();assert.equal(h.video.muted,true);assert.equal(h.tracks.music.volume,.3);assert.equal(h.tracks.effects.volume,.4);assert.equal(h.tracks.voice.volume,.8);await h.transport.play();h.transport.configure({sound:false,musicVolume:.12,effectsVolume:.57,voiceVolume:.94});for(const a of Object.values(h.tracks))assert.equal(a.muted,true);assert.equal(h.tracks.effects.volume,.57);h.video.currentTime=9;h.transport.sync();h.transport.configure({sound:true,musicVolume:.12,effectsVolume:.57,voiceVolume:.94});assert.equal(h.tracks.voice.currentTime,9);assert.equal(h.tracks.voice.muted,false);h.transport.dispose();});
test('buffering, hidden tab and seeking stop stems, with no autoplay after visibility returns',async()=>{const h=harness();await h.transport.play();h.video.emit('waiting');assert.equal(h.tracks.voice.paused,true);h.video.currentTime=3;h.video.emit('playing');assert.equal(h.tracks.voice.paused,false);h.transport.setVisible(false);assert.equal(h.video.paused,true);h.transport.setVisible(true);assert.equal(h.video.paused,true);h.transport.dispose();});
test('resource error pauses everything and disposal prevents late completion callbacks',async()=>{const h=harness();await h.transport.play();h.tracks.voice.emit('error');assert.equal(h.video.paused,true);assert.equal(h.errors.length,1);h.transport.dispose();h.video.emit('ended');assert.equal(h.ended(),0);for(const a of Object.values(h.tracks))assert.equal(a.paused,true);});
test('one natural movie end is delegated, not interpreted as a story flag',async()=>{const h=harness();await h.transport.play();h.video.ended=true;h.video.emit('ended');assert.equal(h.ended(),1);assert.equal(h.tracks.voice.paused,true);h.transport.dispose();});
test('a buffering pause may abort a pending stem play without falsely stopping the chapter',async()=>{const h=harness();let reject,attempts=0;h.tracks.voice.play=()=>{attempts++;return new Promise((_,no)=>reject=no);};await h.transport.play();h.transport.sync();h.transport.sync();assert.equal(attempts,1,'only one unresolved play per stem');h.video.emit('waiting');h.video.emit('playing');reject(Object.assign(new Error('play interrupted by pause'),{name:'AbortError'}));await new Promise(resolve=>setTimeout(resolve,0));assert.deepEqual(h.errors,[]);assert.equal(h.video.paused,false);h.tracks.voice.play=Medium.prototype.play;h.transport.sync();assert.equal(h.tracks.voice.paused,false);h.transport.dispose();});
test('a genuine stem autoplay or decoder rejection still stops playback and exposes recovery',async()=>{const h=harness();h.tracks.voice.play=async()=>{throw Object.assign(new Error('permission'),{name:'NotAllowedError'});};await h.transport.play();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(h.video.paused,true);assert.equal(h.errors.length,1);h.transport.dispose();});
