import {MEAL_FOODS,MEAL_TOPPINGS,MEAL_STOPS,MEAL_ROUNDS,normalizeMealProgress,transitionMeal,mealSummary,deriveMealTask} from '../meal-relay.js';
import './meal-relay.css';
const escape = value => String(value ?? '').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const check = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m5 12 4.5 4.5L19 7" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const arrow = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const bowl = (contents, color='#527f70') => `<ellipse cx="90" cy="111" rx="63" ry="9" fill="#32574e15"/><path d="M27 65h126c-4 26-24 46-63 46S31 91 27 65Z" fill="${color}" stroke="#3e6459" stroke-width="2"/><path d="M35 81c11 16 31 24 55 24s45-8 55-24" fill="none" stroke="#b2cbb15c" stroke-width="2"/><ellipse cx="90" cy="65" rx="64" ry="25" fill="#faf1d7" stroke="#3e6459" stroke-width="2"/>${contents}`;
const foodArt = {
 noodles: bowl('<ellipse cx="90" cy="65" rx="55" ry="19" fill="#c89654"/><g stroke="#f2cd78" stroke-width="4" fill="none" stroke-linecap="round"><path d="M49 64c-8-18 35-17 63-8s-31 17-51 11 16-16 50-5 8 18-12 17"/><path d="M67 48c-9 10 56 10 62 18s-44 6-63 7m-22-4c9 9 29 7 36 8M82 53c-24 0-26 14-8 14s30-11 48-5"/></g><g class="meal-herbs" stroke="#547d52" stroke-width="4" stroke-linecap="round"><path d="m62 54 4 2m38 14 3-4m11-8 4 2m-48 15 3-2"/></g>'),
 doupi: '<ellipse cx="90" cy="111" rx="67" ry="9" fill="#32574e15"/><path d="m17 57 118-12 30 40-117 18Z" fill="#e8e4c9" stroke="#719083" stroke-width="2"/><path d="m23 61 109-11 24 29-107 16Z" fill="#faf4da"/><g stroke="#ba884c" stroke-width="1.5"><path d="m33 59 33-4 14 24-33 5Z" fill="#e9b954"/><path d="m69 55 33-4 14 23-33 5Z" fill="#ecc563"/><path d="m104 51 28-3 15 22-28 4Z" fill="#e9b954"/><path d="m47 84 33-5v11l-31 5Z" fill="#e9d4a0"/><path d="m83 79 33-5v11l-32 5Z" fill="#e9d4a0"/><path d="m119 74 28-4-1 11-27 4Z" fill="#e9d4a0"/></g><g fill="#b8813f"><ellipse cx="54" cy="66" rx="4" ry="2"/><ellipse cx="97" cy="64" rx="3" ry="2"/><ellipse cx="124" cy="59" rx="4" ry="2"/><ellipse cx="66" cy="72" rx="3" ry="2"/></g><g class="meal-herbs" stroke="#5d8150" stroke-width="3" stroke-linecap="round"><path d="m56 60 5 3m28-6 4 2m18 9 3-3m20-4 4 3"/></g>',
 soup: bowl('<ellipse cx="90" cy="65" rx="55" ry="19" fill="#c79d6d"/><g fill="#f0d8b0" stroke="#cfac79" stroke-width="1.5"><ellipse cx="69" cy="60" rx="17" ry="10" transform="rotate(-17 69 60)"/><ellipse cx="108" cy="70" rx="17" ry="10" transform="rotate(12 108 70)"/></g><g fill="#bc915f"><ellipse cx="63" cy="58" rx="2.5" ry="2"/><ellipse cx="72" cy="55" rx="2.5" ry="2"/><ellipse cx="76" cy="62" rx="2.5" ry="2"/><ellipse cx="66" cy="65" rx="2.5" ry="2"/><ellipse cx="101" cy="67" rx="2.5" ry="2"/><ellipse cx="110" cy="65" rx="2.5" ry="2"/><ellipse cx="115" cy="72" rx="2.5" ry="2"/><ellipse cx="105" cy="75" rx="2.5" ry="2"/></g><path d="m90 51 12 2-7 9-12-3Z" fill="#ad8060"/><g class="meal-herbs" stroke="#6b8550" stroke-width="3" stroke-linecap="round"><path d="m48 64 5 2m38 8 4-2m27-13 4 2"/></g>','#927e5e'),
};
const steam = '<g class="meal-steam" fill="none" stroke="#a68d6080" stroke-width="1.5" stroke-linecap="round"><path d="M65 33c-8-8 7-11 0-19"/><path d="M88 28c-8-8 7-11 0-19"/><path d="M111 34c-8-8 7-11 0-19"/></g>';
export function mealFoodPicture(foodId,{scallion='on',chili='none'}={}) {return `<svg viewBox="0 0 180 128" data-scallion="${escape(scallion||'none')}" aria-hidden="true" focusable="false">${foodArt[foodId] || foodArt.doupi}${chili==='on'?'<g fill="#ae6144"><path d="m71 65 4-3 3 4-5 2Zm16-9 5 1-1 4-4-1Zm26 9 4 2-2 3-4-2Z"/></g>':''}${steam}</svg>`;}
const basket = '<svg viewBox="0 0 140 100" aria-hidden="true"><ellipse cx="70" cy="87" rx="53" ry="6" fill="#31584b18"/><path d="M43 37V24c0-20 54-20 54 0v13" fill="none" stroke="#976d43" stroke-width="6"/><path d="m16 35 9 49h90l9-49Z" fill="#c49b60" stroke="#8c6c45" stroke-width="2"/><path d="m15 35 11 12h87l12-12Z" fill="#e0bf83" stroke="#8c6c45" stroke-width="2"/><path d="M33 45v37m15-37v37m15-37v37m15-37v37m15-37v37m14-37v37M22 54h99M24 67h94M25 78h91" stroke="#89683f66" stroke-width="2"/><path d="m26 27 29 4 18-7 43 6v10l-90 1Z" fill="#7b9984"/><path d="m32 31 30 5 11-8 39 5" fill="none" stroke="#aabda0" stroke-width="2"/><rect x="49" y="52" width="43" height="26" rx="3" fill="#fff0cc" stroke="#ae8b59"/><path d="M59 61h23m-23 7h17" fill="none" stroke="#7e9273" stroke-width="2"/></svg>';
const littleDish = field => `<svg viewBox="0 0 80 46" aria-hidden="true"><ellipse cx="40" cy="30" rx="31" ry="11" fill="#4c766a"/><ellipse cx="40" cy="25" rx="31" ry="12" fill="#f7ecd0" stroke="#6e8d77"/><ellipse cx="40" cy="24" rx="23" ry="8" fill="${field === 'scallion' ? '#7c9861' : '#b97550'}"/>${field==='scallion' ? '<g fill="none" stroke="#c7d08f" stroke-width="2"><circle cx="28" cy="23" r="3"/><circle cx="39" cy="20" r="3"/><circle cx="49" cy="25" r="3"/></g>' : '<g fill="#e8af61"><ellipse cx="28" cy="23" rx="2" ry="1"/><ellipse cx="42" cy="20" rx="2" ry="1"/><ellipse cx="50" cy="25" rx="2" ry="1"/></g>'}</svg>`;
function resolveRound(roundId) { const round = Object.hasOwn(MEAL_ROUNDS,roundId) ? MEAL_ROUNDS[roundId] : null; if (!round) throw new RangeError(`Unknown meal round: ${String(roundId)}`); return round; }

/** The caller pauses the world while this workbench is mounted. Every edit is
 * reported immediately; closing the panel never discards a partial lunchbox. */
export function mountMealPacking(root,{progress,roundId='evening',onChange=()=>{},onReady=()=>{},onCancel=()=>{}}={}) {
 const round = resolveRound(roundId); let current = normalizeMealProgress(progress), selected = round.orders.find(item=>!current.rounds[roundId].boxes[item.id].sealed)?.id || round.orders[0].id;
 let message = '先读左边的便签。装什么、怎么放、给谁，确认好了再封盒。', tone='', disposed=false, readyIssued=false;
 if (!current.rounds[roundId].started) { const result=transitionMeal(current,{type:'start',roundId});current=result.progress;onChange(current,result); }
 root.innerHTML='<section class="meal-packing" aria-label="热食接力分装台"></section>';
 const game=root.querySelector('.meal-packing');
 const currentBox = () => current.rounds[roundId].boxes[selected];
 function render(focusKey) {
  if(disposed)return;
  const item=round.orders.find(item=>item.id===selected), box=currentBox(), summary=mealSummary(current,roundId), stop=MEAL_STOPS[item.stopId];
  const toppingName=field=>MEAL_TOPPINGS[field].options.find(option=>option.id===box[field])?.name || '还没选';
  game.innerHTML=`<header class="meal-packing__header"><div><span class="meal-kicker">${escape(round.subtitle)} · 街坊小便签</span><h3>${escape(round.title)}</h3><p>${escape(round.intro)}</p></div><div class="meal-packing__progress"><strong>${summary.sealed}<small> / ${summary.total}</small></strong><span>已核对封盒</span></div></header>
   <nav class="meal-orders" aria-label="选择一份街坊便签">${round.orders.map((order,index)=>{const b=current.rounds[roundId].boxes[order.id];return `<button type="button" class="meal-order${selected===order.id?' is-current':''}${b.sealed?' is-sealed':''}" data-meal-order="${order.id}" data-focus="order-${order.id}" aria-pressed="${selected===order.id}"><span class="meal-order__index">0${index+1}</span><span><strong>${escape(order.name)}</strong><small>${escape(MEAL_STOPS[order.stopId].receiver)}接应 · ${b.delivered?'已交到手里':b.sealed?'封好了':'待分装'}</small></span><i>${b.sealed?check:'<span class="meal-order__dot"></span>'}</i></button>`;}).join('')}</nav>
   <div class="meal-workbench"><aside class="meal-note"><span class="meal-note__clip" aria-hidden="true"></span><span class="meal-note__eyebrow">蔡姨记下的口味</span><h4>给${escape(item.name)}</h4><p>${escape(item.note)}</p><div class="meal-note__route"><span>这份交给</span><strong>${escape(stop.receiver)}</strong><small>${escape(stop.name)}</small></div><span class="meal-note__signature">记得，名字别贴反了。<br>—— 蔡姨</span><span class="meal-note__stamp">晴川里 · 热食接力</span></aside>
   <div class="meal-tray"><div class="meal-tray__heading"><span>${box.sealed?'这份，已经照顾好了。':'把一份心意，慢慢装好。'}</span><small>第 ${round.orders.findIndex(order=>order.id===selected)+1} 份 / 共 ${summary.total} 份</small></div><div class="meal-lunchbox${box.sealed?' is-sealed':''}"><div class="meal-lunchbox__rim"></div><div class="meal-lunchbox__food">${box.food?mealFoodPicture(box.food,box):'<div class="meal-lunchbox__empty"><span></span><p>等一口热的</p><small>从右边选好热食</small></div>'}</div><div class="meal-lunchbox__sides">${['scallion','chili'].map(field=>`<span class="meal-small-dish${box[field]==='side'?' is-filled':''}">${box[field]==='side'?littleDish(field):'<svg viewBox="0 0 80 46" aria-hidden="true"><ellipse cx="40" cy="27" rx="29" ry="11" fill="#eee7cf" stroke="#c0c7ae"/><ellipse cx="40" cy="25" rx="22" ry="7" fill="none" stroke="#d1ceb6"/></svg>'}<small>${escape(MEAL_TOPPINGS[field].name)}${box[field]==='side'?' · 另放':''}</small></span>`).join('')}</div><span class="meal-lunchbox__label${box.label?' has-name':''}"><small>这一份给</small><strong>${escape(round.orders.find(order=>order.id===box.label)?.name || '还没贴名字')}</strong></span>${box.sealed?`<span class="meal-lunchbox__seal">${check}<strong>核对妥当</strong><small>${box.delivered?'已经交接':'已封入篮'}</small></span>`:''}</div><div class="meal-tray__contents" aria-label="本盒已选内容">${[{field:'food',text:box.food?MEAL_FOODS[box.food].name:'还没选热食'},...['scallion','chili'].map(field=>({field,text:`${MEAL_TOPPINGS[field].name}：${toppingName(field)}`}))].map(entry=>`<span>${escape(entry.text)}${box[entry.field]&&!box.sealed?`<button type="button" data-meal-remove="${entry.field}" data-focus="remove-${entry.field}" aria-label="取出${escape(entry.text)}">×</button>`:''}</span>`).join('')}</div><p class="meal-tray__care">${box.sealed?'封好的食盒会留在保温篮里。回来，仍是你记好的这一份。':'装错了，只改那一项。没有倒计时，慢一点也没关系。'}</p></div>
   <div class="meal-pantry"><fieldset ${box.sealed?'disabled':''}><legend><span>01</span> 选一份热食</legend><div class="meal-foods">${Object.values(MEAL_FOODS).map(food=>`<button type="button" class="meal-food${box.food===food.id?' is-selected':''}" data-meal-field="food" data-meal-value="${food.id}" data-focus="food-${food.id}" aria-label="${escape(food.name)}" aria-pressed="${box.food===food.id}"><span>${mealFoodPicture(food.id)}</span><strong>${escape(food.name)}</strong>${box.food===food.id?`<i>${check}</i>`:''}</button>`).join('')}</div></fieldset><fieldset ${box.sealed?'disabled':''}><legend><span>02</span> 照顾好口味</legend>${Object.entries(MEAL_TOPPINGS).map(([field,topping])=>`<div class="meal-topping"><span class="meal-topping__art">${littleDish(field)}</span><span class="meal-topping__title">${escape(topping.name)}</span><div class="meal-options" role="group" aria-label="${escape(topping.name)}的放法">${topping.options.map(option=>`<button type="button" data-meal-field="${field}" data-meal-value="${option.id}" data-focus="${field}-${option.id}" class="${box[field]===option.id?'is-selected':''}" aria-pressed="${box[field]===option.id}">${escape(option.name)}</button>`).join('')}</div></div>`).join('')}</fieldset><fieldset ${box.sealed?'disabled':''}><legend><span>03</span> 贴上名字</legend><div class="meal-names">${round.orders.map(order=>`<button type="button" class="${box.label===order.id?'is-selected':''}" data-meal-field="label" data-meal-value="${order.id}" data-focus="label-${order.id}" aria-pressed="${box.label===order.id}">${escape(order.name)}</button>`).join('')}</div></fieldset></div></div>
   <footer class="meal-packing__footer"><div class="meal-packing__feedback" role="status" aria-live="polite" data-tone="${tone}">${tone==='success'?check:''}<p>${escape(message)}</p></div><div class="meal-packing__actions"><button type="button" class="meal-button-secondary" data-meal-cancel data-focus="cancel">先收好，待会儿继续</button>${summary.ready?`<button type="button" class="meal-button-primary" data-meal-ready data-focus="ready">${summary.completed?'看看这一路的回执':'提起保温篮，去交接'}${arrow}</button>`:box.sealed?`<button type="button" class="meal-button-primary" data-meal-next data-focus="next">看看下一张便签${arrow}</button>`:`<button type="button" class="meal-button-primary" data-meal-seal data-focus="seal">核对这份，封好盒${check}</button>`}</div></footer>
   <div class="meal-packing__journey"><span class="is-active">读便签</span><i></i><span class="${summary.ready?'is-active':''}">分装封盒</span><i></i><span>沿主巷亲手交接</span><small>可步行、骑车或开车 · 抵达后下车交接</small></div>`;
  if(focusKey)game.querySelector(`[data-focus="${focusKey}"]`)?.focus({preventScroll:true});
 }
 function apply(action,focusKey) {
  const result=transitionMeal(current,{...action,roundId,orderId:selected});current=result.progress;message=result.message;tone=result.ok?(result.code==='sealed'?'success':''):'attention';
  onChange(current,result);render(result.code==='sealed'?(mealSummary(current,roundId).ready?'ready':'next'):(action.type==='seal'?'seal':focusKey));
 }
 function click(event) {
  const button=event.target.closest('button');if(!button||!game.contains(button)||button.disabled||disposed)return;
  if(button.hasAttribute('data-meal-order')){selected=button.dataset.mealOrder;message=currentBox().sealed?'这份已经核对好，名字和口味都留在食盒上了。':'看看这张便签，再照顾好这一份。';tone='';render(button.dataset.focus);return;}
  if(button.hasAttribute('data-meal-field'))return apply({type:'pack',field:button.dataset.mealField,value:button.dataset.mealValue},button.dataset.focus);
  if(button.hasAttribute('data-meal-remove'))return apply({type:'remove',field:button.dataset.mealRemove});
  if(button.hasAttribute('data-meal-seal'))return apply({type:'seal'},mealSummary(current,roundId).sealed===round.orders.length-1?'ready':'next');
  if(button.hasAttribute('data-meal-next')){selected=round.orders.find(item=>!current.rounds[roundId].boxes[item.id].sealed)?.id || selected;message='上一份已经收好了。接着看看这个人喜欢的口味。';tone='';render(`order-${selected}`);return;}
  if(button.hasAttribute('data-meal-cancel')){onCancel(normalizeMealProgress(current));return;}
  if(button.hasAttribute('data-meal-ready')&&mealSummary(current,roundId).ready&&!readyIssued){readyIssued=true;button.disabled=true;onReady(normalizeMealProgress(current));}
 }
 game.addEventListener('click',click);render();
 const cleanup=()=>{disposed=true;game.removeEventListener('click',click);};
 cleanup.update=value=>{if(disposed)return;current=normalizeMealProgress(value);render();};
 cleanup.getProgress=()=>normalizeMealProgress(current);
 return cleanup;
}

/** Nonmodal companion card. It never completes a delivery; the world interaction
 * supplies the verified player position to the rules at the recipient. */
export function mountMealHUD(root,{progress,roundId='evening',onNavigate=()=>{},onOpenPacking=()=>{}}={}) {
 const round=resolveRound(roundId);let current=normalizeMealProgress(progress),sample={},disposed=false,lastMarkup='';
 const hud=document.createElement('aside');hud.className='meal-hud';hud.setAttribute('aria-label','热食接力进度');root.append(hud);
 function render(){
  if(disposed)return;
  const summary=mealSummary(current,roundId);hud.hidden=!summary.started||summary.completed;
  if(hud.hidden)return;
  const task=deriveMealTask(current,roundId), state=current.rounds[roundId];
  const markup=`<div class="meal-hud__top"><span class="meal-hud__basket">${basket}</span><div><span class="meal-kicker">${escape(round.title)} · 保温篮</span><strong>${summary.ready?`亲手交接 ${summary.delivered} / ${summary.total}`:`已经封盒 ${summary.sealed} / ${summary.total}`}</strong><small>${summary.ready?'两处先去哪边，都可以。':'没装完的，蔡姨替你留在桌上。'}</small></div></div><div class="meal-hud__boxes" aria-label="食盒状态">${round.orders.map(item=>{const box=state.boxes[item.id];return `<span class="${box.delivered?'is-delivered':box.sealed?'is-sealed':''}">${box.delivered?check:'<i></i>'}${escape(item.name)}<small>${box.delivered?'已交':box.sealed?'封好':'待装'}</small></span>`;}).join('')}</div>${summary.ready?`<div class="meal-hud__destinations">${Object.values(MEAL_STOPS).filter(stop=>round.orders.some(item=>item.stopId===stop.id&&!state.boxes[item.id].delivered)).map(stop=>`<button type="button" data-meal-route="${stop.target}"><span><strong>${escape(stop.receiver)}</strong><small>${escape(stop.name)}</small></span>${arrow}</button>`).join('')}</div><p class="meal-hud__hint">${sample.mode&&sample.mode!=='walk'?'抵达后按 F 下车，走近接应的人交盒。':'走近接应的人，按 E 逐份交接。'}</p>`:`<button type="button" class="meal-hud__resume" data-meal-route="${task.target}">回蔡姨的分装台，接着做${arrow}</button><p class="meal-hud__hint">已装好的会保留，不用从头来。</p>`}`;
  if(markup!==lastMarkup){hud.innerHTML=markup;lastMarkup=markup;}
 }
 const click=event=>{const b=event.target.closest('[data-meal-route],[data-meal-resume]');if(!b||!hud.contains(b))return;if(b.hasAttribute('data-meal-resume'))onOpenPacking();else onNavigate(b.dataset.mealRoute);};
 hud.addEventListener('click',click);render();
 const cleanup=()=>{disposed=true;hud.removeEventListener('click',click);hud.remove();};
 cleanup.update=(value,worldSample={})=>{current=normalizeMealProgress(value);sample=worldSample;render();};
 return cleanup;
}
